修改创建样式和标题样式
tiddly-gittly/tiddlywiki-calendar pull request #3
Opened 2022-12-09 08:52 UTC by dongrentianyu

删除了标题里的时区显示。标题通过前缀来实现。样式也修改了一部分，在修改的说明里。

2022-12-09 12:51 UTC, linonetwo requested changes

2022-12-09 12:51 UTC, linonetwo commented on src/tiddlywiki-ui/popup/CreateNewTiddlerPopupFooter.tid
> -<$wikify name="newtitle" text="{{$:/plugins/linonetwo/tw-calendar/settings/prefix}}{{$:/state/Calendar/PageLayout/create-tiddler-caption!!draft.title}}{{$:/state/Calendar/PageLayout/create-tiddler!!d
这里不对吧，前缀后面的实际标题也得带上

2022-12-09 12:51 UTC, linonetwo commented on src/tiddlywiki-ui/popup/CreateNewTiddlerPopup.tid
> +     {{$:/state/Calendar/PageLayout/create-tiddler||$:/core/ui/EditTemplate/tags}}
缩进要对齐

2022-12-09 12:51 UTC, linonetwo commented on src/tiddlywiki-ui/popup/CreateNewTiddlerPopup.tid
> -  <small>Title:{{$:/plugins/linonetwo/tw-calendar/settings/prefix}}{{$:/state/Calendar/PageLayout/create-tiddler-caption!!draft.title}}{{$:/state/Calendar/PageLayout/create-tiddler!!draft.title}}</sm
新标题预览要保留

2022-12-09 12:58 UTC, dongrentianyu commented on src/tiddlywiki-ui/popup/CreateNewTiddlerPopupFooter.tid
> -<$wikify name="newtitle" text="{{$:/plugins/linonetwo/tw-calendar/settings/prefix}}{{$:/state/Calendar/PageLayout/create-tiddler-caption!!draft.title}}{{$:/state/Calendar/PageLayout/create-tiddler!!d
只保留前缀，并移除标题预览才能实现整体的效果。如果这里保留后面的标题，就会把时区格式一起带过来。后面移除标题预览也是因为只保留了前缀。如果有预览的话，caption和text字段都无法编辑。

2022-12-09 12:59 UTC, dongrentianyu commented on src/tiddlywiki-ui/popup/CreateNewTiddlerPopupFooter.tid
> -<$wikify name="newtitle" text="{{$:/plugins/linonetwo/tw-calendar/settings/prefix}}{{$:/state/Calendar/PageLayout/create-tiddler-caption!!draft.title}}{{$:/state/Calendar/PageLayout/create-tiddler!!d
是保留标题后面的，不是“保留后面的标题”，上面打快了，打错字了

2022-12-09 13:04 UTC, dongrentianyu commented on src/tiddlywiki-ui/popup/CreateNewTiddlerPopupFooter.tid
> -<$wikify name="newtitle" text="{{$:/plugins/linonetwo/tw-calendar/settings/prefix}}{{$:/state/Calendar/PageLayout/create-tiddler-caption!!draft.title}}{{$:/state/Calendar/PageLayout/create-tiddler!!d
但我不清楚，是不是因为我这样的修改，导致日历上出现内容溢出，占用下一格的情况。

2022-12-10 06:02 UTC, linonetwo commented on src/tiddlywiki-ui/popup/CreateNewTiddlerPopupFooter.tid
> -<$wikify name="newtitle" text="{{$:/plugins/linonetwo/tw-calendar/settings/prefix}}{{$:/state/Calendar/PageLayout/create-tiddler-caption!!draft.title}}{{$:/state/Calendar/PageLayout/create-tiddler!!d
没太明白你的思路 ，反正这肯定得三个部分拼起来，你只保留第一个不对吧

2022-12-10 06:02 UTC, linonetwo commented
反正你改改再推送下

2022-12-10 06:03 UTC, linonetwo commented on src/tiddlywiki-ui/popup/CreateNewTiddlerPopupFooter.tid
> -<$wikify name="newtitle" text="{{$:/plugins/linonetwo/tw-calendar/settings/prefix}}{{$:/state/Calendar/PageLayout/create-tiddler-caption!!draft.title}}{{$:/state/Calendar/PageLayout/create-tiddler!!d
标题肯定是越完备越长越好，不容易冲突

2022-12-11 05:38 UTC, dongrentianyu commented
标题预览保留了，但只会显示时间前缀和caption，时区不会显示。常用标签放在左边，新添加标签放在右边。

现在的问题就是点击一格，会占用两格，甚至在一周显示里，会往下占用两三格。一开始我以为是我修改后出现的bug，后面测试发现是原生就有的bug。不知道其他人有没有这个问题。我自己使用过程中也有这样的问题。

这可能需要修改js文件，我就没有再继续看下了。最近时间也是不是很充裕，只能先这样了。

2022-12-11 09:15 UTC, linonetwo commented
先合了，我看看情况

2022-12-11 09:15 UTC, merged